# Generated by Django 5.1 on 2024-11-21 16:01

import base_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_comu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion_Producto',
            fields=[
                ('id_cond', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cond', models.CharField(max_length=50)),
                ('desc_cond', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Publicacion',
            fields=[
                ('id_estpubli', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estpubli', models.CharField(max_length=50)),
                ('desc_estpubli', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Usuario',
            fields=[
                ('id_estusu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estusu', models.CharField(max_length=50)),
                ('desc_estusu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_mar', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_Registro',
            fields=[
                ('id_metreg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_metreg', models.CharField(max_length=50)),
                ('desc_metreg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_reg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=50)),
                ('desc_rol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id_tipoeven', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipoeven', models.CharField(max_length=50)),
                ('desc_tipoeven', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ciu', models.CharField(max_length=50)),
                ('id_comu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tfno', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('ciu', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=700)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to=base_app.models.get_file_path)),
                ('id_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.categoria')),
                ('id_cond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.condicion_producto')),
                ('id_mar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_foto', models.CharField(max_length=200)),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='base_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.region'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('fech_reg', models.DateTimeField()),
                ('met_reg', models.CharField(max_length=200)),
                ('ip_reg', models.CharField(max_length=45)),
                ('disp_reg', models.CharField(blank=True, max_length=100, null=True)),
                ('id_metreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.metodo_registro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(max_length=50)),
                ('apepat_usu', models.CharField(max_length=50)),
                ('apepmat_usu', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('sexo_usu', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
                ('contra_hash', models.CharField(max_length=255)),
                ('fech_reg', models.DateTimeField(blank=True, null=True)),
                ('fech_actualiusu', models.DateTimeField(blank=True, null=True)),
                ('id_ciu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.ciudad')),
                ('id_estusu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.estado_usuario')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publi', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_publi', models.CharField(max_length=100)),
                ('desc_publi', models.CharField(max_length=500)),
                ('precio', models.FloatField()),
                ('fech_publi', models.DateTimeField(blank=True, null=True)),
                ('fech_actualipubli', models.DateTimeField(blank=True, null=True)),
                ('id_estpubli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.estado_publicacion')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.producto')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('fech_login', models.DateTimeField()),
                ('ip_login', models.CharField(blank=True, max_length=45, null=True)),
                ('disp_login', models.CharField(blank=True, max_length=100, null=True)),
                ('est_login', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=10)),
                ('ulti_login', models.DateTimeField(blank=True, null=True)),
                ('res_token', models.CharField(blank=True, max_length=255, null=True)),
                ('fech_exptoken', models.DateTimeField(blank=True, null=True)),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Publicacion',
            fields=[
                ('id_hist', models.AutoField(primary_key=True, serialize=False)),
                ('desc_hist', models.CharField(blank=True, max_length=200, null=True)),
                ('prec_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prec_nue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fech_even', models.DateTimeField()),
                ('id_estpubli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.estado_publicacion')),
                ('id_publi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.publicacion')),
                ('id_tipoeven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.tipo_evento')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.usuario')),
            ],
        ),
    ]
